version: '2.1'

services:

  test:
    extends:
      file: docker-compose.yml
      service: base-app
    command: scripts/container/test-watch
    links:
      - sexual-health-service-finder-db:es
    volumes:
      - node_modules:/code/node_modules
      - .:/code

  tests-unit:
    extends:
      file: docker-compose.yml
      service: base-app
    command: yarn run test-unit-watch
    volumes:
      - node_modules:/code/node_modules
      - .:/code

  tests-integration:
    extends:
      file: docker-compose.yml
      service: base-app
    command: scripts/container/integration-tests
    links:
      - sexual-health-service-finder-db:es
    volumes:
      - node_modules:/code/node_modules
      - .:/code

  test-ci:
    extends:
      file: docker-compose.yml
      service: base-app
    command: scripts/container/ci-tests
    user: root
    links:
      - sexual-health-service-finder-db:es
    volumes:
      - node_modules:/code/node_modules
    environment:
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      TRAVIS: ${TRAVIS}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      TRAVIS_COMMIT: ${TRAVIS_COMMIT}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}


  sexual-health-service-finder-db:
    image: "nhsuk/elasticsearch-updater-snapshot:${elasticsearch_updater_snapshot_docker_image_tag-20180308}"

volumes:
  node_modules:
