version: '2.1'

services:

  test:
    extends:
      file: docker-compose.yml
      service: base-app
    command: yarn run test-watch
    volumes:
      - sh-test-node_modules:/code/node_modules
      - .:/code

  tests-unit:
    extends:
      file: docker-compose.yml
      service: base-app
    command: yarn run test-unit-watch
    volumes:
      - sh-test-unit-node_modules:/code/node_modules
      - .:/code

  tests-integration:
    extends:
      file: docker-compose.yml
      service: base-app
    command: yarn run test-integration-watch
    volumes:
      - sh-test-integration-node_modules:/code/node_modules
      - .:/code

  test-ci:
    extends:
      file: docker-compose.yml
      service: base-app
    command: yarn run test-ci
    user: root
    volumes:
      - sh-test-ci-node_modules:/code/node_modules
    environment:
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      TRAVIS: ${TRAVIS}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      TRAVIS_COMMIT: ${TRAVIS_COMMIT}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}

volumes:
  sh-test-node_modules:
  sh-test-unit-node_modules:
  sh-test-integration-node_modules:
  sh-test-ci-node_modules:
